apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: e2e-fbc-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/e2e-fbc-application/e2e-fbc-component@sha256:29d8d0ddcc711432465df2184c1c9bda84e8c4799bd03dbab5550b440d041be8
        name: fbc
        resources: {}
status: {}
